# Vectorization exercise for Week 2 of Deep Learning Specialziation

In [3]:
import numpy as np

a = np.array([1, 2, 3, 4])

In [4]:
print(a)

[1 2 3 4]


In [5]:
import time

In [30]:
c = 0
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(f"{round(c, 2):,}")
print("Vectorized version:" + str(round(1000*(toc-tic), 2)) + "ms")

c = 0
tic = time.time()

for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(f"{round(c, 2):,}")
print("For loop:" + str(round(1000*(toc-tic), 2)) + "ms")

249,871.98
Vectorized version:1.97ms
249,871.98
For loop:323.99ms


Wow!! It's way better to vectorize your code!

## Another example of vector calculations - this time using broadcasting


In [34]:
A = np.array([[56, 0, 4.4, 68],
[1.2, 104, 52, 8],
[1.8, 135, 0.99, 0.9]])

In [36]:
A

array([[ 56.  ,   0.  ,   4.4 ,  68.  ],
       [  1.2 , 104.  ,  52.  ,   8.  ],
       [  1.8 , 135.  ,   0.99,   0.9 ]])

In [51]:
# Here we say sum(axis = 0) to mean sum vertically
cal = A.sum(axis=0)
cal

array([ 59.  , 239.  ,  57.39,  76.9 ])

In [50]:
percentage = np.round(100*A/cal.reshape(1,4), 2)
percentage

array([[94.92,  0.  ,  7.67, 88.43],
       [ 2.03, 43.51, 90.61, 10.4 ],
       [ 3.05, 56.49,  1.73,  1.17]])

In [54]:
b = np.array([100, 300, 400])
c = np.array([[2],
[3]])

In [55]:
b * c

array([[ 200,  600,  800],
       [ 300,  900, 1200]])